version: '3.3'

services: 
  web:
    container_name: 'markers.backend'
    build: ./backend
    command: gunicorn geoln_test_markers.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    volumes: 
      - ./static:/static
      - ./media:/media
    env_file: 
      - ./.env

  nginx:
    restart: always
    image: nginx:1.19.0-alpine
    container_name: 'markers.nginx'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - 80:80
    depends_on: 
      - web

  psql:
    container_name: 'markers.postgres'
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - psql:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: 
      - ./.env

volumes: 
  psql: