# Generated by Django 3.2.4 on 2021-06-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=511, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField(verbose_name='Координата по X')),
                ('pos_y', models.FloatField(verbose_name='Координата по Y')),
                ('text', models.CharField(max_length=127, verbose_name='Текст маркера')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markers.picture')),
                ('to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='markers.picture')),
            ],
        ),
    ]
