# Generated by Django 3.1.4 on 2021-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20210614_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, max_length=511, null=True, verbose_name='Описание'),
        ),
    ]
